sudo: required
language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - env: WP_VERSION=nightly

services:
  - mysql

addons:
  # instead of adding a line, in the `before_install` or `install`
  # sections to install packages using `apt-get install...` I simply
  # delegate the task to Travis
  apt:
    packages:
      - php7.0-fpm
      - php7-mysql
      - nginx
hosts:
  - coursacheit.conf
env:
  # here I define some environment variables I will be able to use
  # in scripts and in the PHP application itself
  # e.g `$SITE_FOLDER` will return `/tmp/site` in a bash script
  # while `$siteFolder = getenv('SITE_FOLDER');` will return the same
  # value in a PHP script
  global:
    - SITE_URL="http://coursacheit.conf"
    - SITE_DOMAIN="coursacheit.conf"
    - DB_NAME="bonus_program"

before_install:
  # create the databases that will be used by the site using `mysql` binary
  # user is `root`, password is empty and host is `localhost`
  # mysql --user="bonus" --database="$DB_NAME" --password="bonus" < "./configs/migrations/init.sql"
  - mysql -u "create database IF NOT EXISTS $DB_NAME;" -uroot
  - mysql -u bonus --default-character-set=utf8 --password="bonus" < configs/migrations/init.sql

install:
  # install Composer dependencies
  - composer install --prefer-dist

  # copy the Nginx configuration file for the site among the available ones from
  # the `build` folder; the styles of the Nginx configuration file I'm using is
  # specific to WordPress (see below) so use whatever you need to use.
  # Given the current environment configuration it will be copied to `/etc/nginx/sites-available/site.localhost`
  - sudo cp configs/coursacheit.conf /etc/nginx/sites-available/$SITE_DOMAIN

  # using sed replace the placeholder text in the Nginx configuration file to use the
  # correct site folder path and domain
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN
  - sudo sed -e "s?%SITE_DOMAIN%?$SITE_DOMAIN?g" --in-place /etc/nginx/sites-available/$SITE_DOMAIN

  # enable the site by creating a symbolic link in the `sites-enabled` folder
  - sudo ln -s /etc/nginx/sites-available/$SITE_DOMAIN /etc/nginx/sites-enabled/

before_script:
  - sudo service php7.0-fpm restart
  - sudo service nginx restart

script:
  - ./generate.py
  - curl http://coursacheit.conf
