<?php
class Controller_Report extends Controller
{

    function __construct()
    {
        $this->model = new ModelReport();
        $this->view = new View();
    }

    function action_index()
    {
        $data = $this->model->action();
        $this->view->render('report_view.php', 'base_view.php', $data);
    }
    function action()
    {
        parent::action(); // TODO: Change the autogenerated stub
    }
    function action_bonus_miles_hist() {
        $sql = 'SELECT t.flight_id, t.departure, SUM(d.cur_value) FROM detail d
JOIN ticket t ON (t.uid = d.ticket_id) 
GROUP BY t.flight_id, t.departure;';
        $data = DataBase::query($sql);
        $this->view->render('new_report_view.php', 'base_view.php', $data);
    }
    function action_booking_from() { // TODO: add t.class in sql statement
            $sql = 'select f.dep_airport, t.departure, COUNT(*) from ticket t
join flight f on (t.flight_id = f.uid) where year(t.departure) = ?
group by f.dep_airport, t.departure';
        $user_data = [$_GET['booking_from']];
        $data = DataBase::paramQuery($sql, $user_data);
        $this->view->render('new_report_view.php', 'base_view.php', $data);
    }
}
