<?php
class Controller_Report extends Controller
{

    function __construct()
    {
        $this->model = new ModelReport();
        $this->view = new View();
    }

    function action_index()
    {
        $data = $this->model->action();
        $this->view->render('report_view.php', 'base_view.php', $data);
    }
    function action()
    {
        parent::action(); // TODO: Change the autogenerated stub
    }
    function action_bonus_miles_hist() {
        echo 'bonus miles';
        parent::action();
    }
    function action_booking_from() {
        echo 'booking from';
        parent::action();
    }
}
